BR python-webob
thus fixing downstream build:
oslo.config option ciphers
Exception occurred:
  File "/usr/lib/python2.7/site-packages/routes/middleware.py", line 5,
in <module>
    from webob import Request
ImportError: No module named webob

Change-Id: I1e4e8f793af0efc1ef1fd05012e91dd97b774707